platform: linux
image_resource:
  type: docker-image
  source:
    repository: gcr.io/cf-routing/cf-k8s-networking/k8s-deploy

inputs:
  - name: env-metadata
  - name: cf-k8s-networking-ci
  - name: cf-k8s-networking

run:
  path: cf-k8s-networking-ci/ci/tasks/scale/run-scale-tests.sh

params:
  NUMBER_OF_APPS: 100
